### ISSUE TITLE
Add an option to print relative timings for news items

### ISSUE THREAD

**Issue by cryoff** [datacoffee/topicsbot#4]
Right now the timings of the "news" entities are given in absolute 24h format.
We would also like to set certain time instant as a "beginning of a podcast" and re-compute the absolute timings into the relative ones, which can be then used as chapter markers in the resulting podcast episode.

**Comment by aleksandrgordienko** [comment]
I thought about the new command, i.e. /start_podast or /whatever. We send the command at the time of starting recording and the bot provides us with a keyboard and fixes the exact times of choosing a new topic.

The keyboard could look like this: <img src=https://core.telegram.org/file/811140184/1/5YJxx-rostA/ad3f74094485fb97bd>

**Comment by aleksandrgordienko** [comment]
Upd: it looks like keyboard wouldn't be useful with more than 5-10 news..

**Comment by cryoff** [comment]
With more than 5-10 news it is easier to have something like "#current <ID>" or "#current <some excerpt from news>". Since our IDs are not easy to use, we can just use some kind of excerpt like "jukebox" and do the naive (maybe a bit fuzzy) search in the description of news that corresponds to that excerpt.

Or another option is to have a certain link/button for each news in the "/list" output that is clickable.

**Comment by aleksandrgordienko** [comment]
Added clickable /chapter_N links to the /list output
PR #17
